USE greenmind;
DROP TABLE IF EXISTS gare;
CREATE TABLE gare
(
    id INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
    code_uic VARCHAR(50) NULL COMMENT '',
    libelle VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    fret VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    voyageurs VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    code_ligne VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    rg_troncon INT(11) NULL DEFAULT NULL COMMENT '',
    pk VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    commune VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    departemen VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    idreseau VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    idgaia VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    x_l93 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    y_l93 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    x_wgs84 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    y_wgs84 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    c_geo VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    geo_point VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    geo_shape VARCHAR(100) NULL DEFAULT NULL COMMENT '',
    PRIMARY KEY (id)
);
