USE greenmind;
DROP TABLE IF EXISTS gare;
CREATE TABLE gare
(
    id INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
    code_uic VARCHAR(50) NULL COMMENT '',
    libelle VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    fret VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    voyageurs VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    code_ligne VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    rg_troncon INT(11) NULL DEFAULT NULL COMMENT '',
    pk VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    commune VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    departemen VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    idreseau VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    idgaia VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    x_l93 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    y_l93 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    x_wgs84 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    y_wgs84 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    c_geo VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    geo_point VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    geo_shape VARCHAR(100) NULL DEFAULT NULL COMMENT '',
    PRIMARY KEY (id)
);

USE greenmind;
DROP TABLE IF EXISTS car_co2;
CREATE TABLE car_co2
(
    id INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
    marque VARCHAR(50) NULL COMMENT '',
    modele_dossier VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    modele_commercial VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    designation_commerciale VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    cnit VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    tvv VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    carburant VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    hybride VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    puissance_administrative INT(11) NULL DEFAULT NULL COMMENT '',
    puissance_maximale DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    boite_de_vitesse VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    consommation_urbaine DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    consommation_extra_urbaine DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    consommation_mixte DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    co2 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    co_type_I DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    hc DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    nox DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    hc_nox DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    particules DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    masse_vide_euro_min INT(11) NULL DEFAULT NULL COMMENT '',
    masse_vide_euro_max INT(11) NULL DEFAULT NULL COMMENT '',
    champ_v9 VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    annee VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    carrosserie VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    gamme VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    PRIMARY KEY (id)
);

USE greenmind;
DROP TABLE IF EXISTS gare;
CREATE TABLE gare
(
    id INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
    code_uic VARCHAR(50) NULL COMMENT '',
    libelle VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    fret VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    voyageurs VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    code_ligne VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    rg_troncon INT(11) NULL DEFAULT NULL COMMENT '',
    pk VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    commune VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    departemen VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    idreseau VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    idgaia VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    x_l93 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    y_l93 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    x_wgs84 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    y_wgs84 DECIMAL(50,15) NULL DEFAULT NULL COMMENT '',
    c_geo VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    geo_point VARCHAR(50) NULL DEFAULT NULL COMMENT '',
    geo_shape VARCHAR(100) NULL DEFAULT NULL COMMENT '',
    PRIMARY KEY (id)
);